app:
  name: fitness_tracking_app
  env: dev
postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "azamat"
  database: "fitness"
server:
  http:
    host: "localhost"
    port: "8080"