// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type PasswordResetToken struct {
	ID         int32
	UserID     sql.NullInt32
	Token      string
	Expiration time.Time
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	Profile      pqtype.NullRawMessage
}

type Workout struct {
	ID          int32
	UserID      int32
	Name        string
	Description sql.NullString
	Date        time.Time
	CreateAt    time.Time
	UpdateAt    time.Time
}
